server:
  port: 8081

spring:
  application:
    name: cours-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://imad:4444qqqq@cluster0.aqwy2gi.mongodb.net/cours_db?retryWrites=true&w=majority&appName=Cluster0}
    rest:
      base-path: /api/data

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGeneration123456789}
  expiration: 86400000

graphql:
  servlet:
    mapping: /graphql
